required by asSVG
```
> python asSVG.py ..\data\moose_pha.shp y 3 ID Area test.svg
ERROR: [Errno 2] No such file or directory: 'asSVG.py/Tango-Palette.gpl'
[Errno 2] No such file or directory: 'asSVG.py/Tango-Palette.gpl'
```